[package]
name = "img_to_ascii"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.1"
clap = { version = "4.1.14", features = ["derive"] }

[dev-dependencies]
image = "0.25.1"  # For tests, ensure it's also available
